//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

class Benefit
{
	protected float base_value;
	protected float modifier;

	public Benefit ()
	{
		base_value = 1.0f;
		modifier = 1.0f;
	}

	public Benefit (float b)
	{
		base_value = b;
		modifier = 1.0f;
	}

	public Benefit (float b, float m)
	{
		base_value = b;
		modifier = m;
	}

	public float Value ()
	{
		return base_value * modifier;
	}

	public void SetBase (float b)
	{
		base_value = b;
	}

	public void SetModifier (float m)
	{
		modifier = m;
	}

	public void AddBase (float b)
	{
		base_value += b;
	}

	public void AddModifier (float m)
	{
		modifier += m;
	}
}


