//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

static class Calculate
{
	#region Strength

	public static float maxHP (float points)
	{
		//todo
		return 50.0f;
	}

	public static float combat (float points)
	{
		//todo
		return 1.0f;
	}

	#endregion

	#region Agility

	public static float movespeed (float points)
	{
		//todo
		return 5.0f;
	}

	public static float stamina_regen (float points)
	{
		//todo
		return 5.0f;
	}

	#endregion

	#region Energy



	#endregion
}


