//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Dinosaur
{
	public Attributes.Strength strength;
	public Attributes.Agility agility;
	public Attributes.Energy energy;

	public Dinosaur ()
	{
		strength = new Attributes.Strength ();
		agility = new Attributes.Agility ();
		energy = new Attributes.Energy ();
	}
}


