//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Attributes
{
	public class Agility : Attribute
	{
		private Benefit movespeed;
		private Benefit stamina_regen;

		public Agility () : base()
		{
			movespeed = new Benefit ();
			stamina_regen = new Benefit ();
			GetBenefitsFromPoints ();
		}

		protected override void GetBenefitsFromPoints ()
		{
			float p = Points ();
			movespeed.SetBase (Calculate.movespeed (p));
			stamina_regen.SetBase (Calculate.stamina_regen (p));
		}

		public float Movespeed ()
		{
			return movespeed.Value ();
		}

		public float StaminaRegen ()
		{
			return stamina_regen.Value ();
		}

		public void AddMovespeedBase (float b)
		{
			movespeed.AddBase (b);
		}

		public void AddMovespeedModifier (float m)
		{
			movespeed.AddModifier (m);
		}

		public void AddStaminaRegenBase (float b)
		{
			stamina_regen.AddBase (b);
		}

		public void AddStaminaRegenModifier (float m)
		{
			stamina_regen.AddModifier (m);
		}
	}
}

