//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public abstract class Attribute
{
	private float points;

	public Attribute ()
	{
		points = 1.0f;
	}

	protected float Points ()
	{
		return points;
	}

	protected void AddPoints (float p)
	{
		points += p;
		GetBenefitsFromPoints ();
	}

	protected abstract void GetBenefitsFromPoints ();
}


