//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Attributes
{
	public class Strength : Attribute
	{
		private Benefit maxHP;
		private Benefit combatStrength;
		
		public Strength () : base()
		{
			maxHP = new Benefit ();
			combatStrength = new Benefit ();
			GetBenefitsFromPoints ();
		}
		
		protected override void GetBenefitsFromPoints ()
		{
			float p = Points ();
			maxHP.SetBase (Calculate.maxHP (p));
			combatStrength.SetBase (Calculate.combat (p));
		}
		
		public float MaxHP ()
		{
			return maxHP.Value ();
		}
		
		public float CombatStrength ()
		{
			return combatStrength.Value ();
		}
		
		public void AddMaxHPBase (float b)
		{
			maxHP.AddBase (b);
		}
		
		public void AddMaxHPModifier (float m)
		{
			maxHP.AddModifier (m);
		}
		
		public void AddCombatStrengthBase (float b)
		{
			combatStrength.AddBase (b);
		}
		
		public void AddCombatStrengthModifier (float m)
		{
			combatStrength.AddModifier (m);
		}
	}
}

